import PDFDocument from 'pdfkit';
import { supabase } from '../../lib/supabase';

export default async function handler(req, res) {
  if (req.method !== 'GET') {
    return res.status(405).json({ error: 'Method not allowed' });
  }

  try {
    const { id } = req.query;

    if (!id) {
      return res.status(400).json({ error: 'Audit ID required' });
    }

    // Fetch audit from Supabase
    const { data: audit, error } = await supabase
      .from('audits')
      .select('*')
      .eq('id', id)
      .single();

    if (error || !audit) {
      console.error('Audit not found:', error);
      return res.status(404).json({ error: 'Audit not found' });
    }

    // Parse JSON fields if they're strings
    const recommendations = typeof audit.recommendations === 'string' 
      ? JSON.parse(audit.recommendations || '[]') 
      : audit.recommendations || [];
    const tools = typeof audit.tools === 'string' 
      ? JSON.parse(audit.tools || '[]') 
      : audit.tools || [];

    // Create PDF
    const doc = new PDFDocument({ margin: 40 });

    // Set response headers for PDF download
    res.setHeader('Content-Type', 'application/pdf');
    res.setHeader('Content-Disposition', `attachment; filename="audit-report-${audit.id}.pdf"`);

    // Pipe to response
    doc.pipe(res);

    // Header
    doc.fontSize(24).font('Helvetica-Bold').text('AI Spend Audit Report', { align: 'center' });
    doc.fontSize(12).font('Helvetica').text(`Report ID: ${audit.id}`, { align: 'center' });
    doc.moveDown();

    // Savings Summary
    doc.fontSize(14).font('Helvetica-Bold').text('Savings Summary', { underline: true });
    doc.fontSize(11).font('Helvetica');
    doc.text(`Monthly Savings: $${audit.total_monthly_savings || 0}`, { indent: 10 });
    doc.text(`Annual Savings: $${audit.total_annual_savings || 0}`, { indent: 10 });
    doc.text(`Current Monthly Spend: $${audit.total_current_spend || 0}`, { indent: 10 });
    doc.moveDown();

    // Company Info
    if (audit.team_size || audit.use_case) {
      doc.fontSize(14).font('Helvetica-Bold').text('Your Information', { underline: true });
      doc.fontSize(11).font('Helvetica');
      if (audit.team_size) doc.text(`Team Size: ${audit.team_size}`, { indent: 10 });
      if (audit.use_case) doc.text(`Primary Use Case: ${audit.use_case}`, { indent: 10 });
      doc.moveDown();
    }

    // Recommendations
    if (recommendations && recommendations.length > 0) {
      doc.fontSize(14).font('Helvetica-Bold').text('Recommendations', { underline: true });
      doc.moveDown(0.5);

      recommendations.forEach((rec, idx) => {
        doc.fontSize(11).font('Helvetica-Bold').text(`${idx + 1}. ${rec.tool || 'Tool'}`, { indent: 10 });
        doc.fontSize(10).font('Helvetica');
        doc.text(`Current: ${rec.currentPlan || 'N/A'} - $${rec.currentSpend || 0}/month`, { indent: 20 });
        doc.text(`Recommended: ${rec.recommendedPlan || 'N/A'} - $${rec.recommendedSpend || rec.currentSpend}/month`, { indent: 20 });
        doc.text(`Monthly Savings: $${rec.monthlySavings || 0}`, { indent: 20 });
        doc.text(`Reason: ${rec.reason || 'No details'}`, { indent: 20, width: 400 });
        doc.moveDown(0.3);
      });
      doc.moveDown();
    }

    // Footer
    doc.fontSize(9).font('Helvetica').text('Generated by AI Spend Audit Tool', { align: 'center' });
    doc.text(`Date: ${new Date().toLocaleDateString()}`, { align: 'center' });

    // Finalize PDF
    doc.end();
  } catch (error) {
    console.error('Error generating PDF:', error);
    res.status(500).json({ error: 'Failed to generate PDF' });
  }
}
