import PDFDocument from 'pdfkit'
import { supabase } from '@/lib/supabase'
import {
  drawPageBackground,
  drawHorizontalLine,
  drawSectionHeader,
  drawStatCard,
  drawToolRow,
  addPageNumber,
  addFooter,
  checkPageBreak,
} from '@/lib/pdfHelpers'
import { PRICING_DATA } from '@/lib/pricingData'

function formatCurrency(value) {
  return `$${Number(value || 0).toLocaleString()}`
}

function formatDate(isoString) {
  const date = isoString ? new Date(isoString) : new Date()
  if (Number.isNaN(date.getTime())) return new Date().toLocaleDateString('en-US')
  return date.toLocaleDateString('en-US', {
    month: 'long',
    day: 'numeric',
    year: 'numeric',
  })
}

function getToolName(toolKey) {
  if (!toolKey) return 'Unknown tool'
  if (typeof toolKey === 'string') {
    return PRICING_DATA[toolKey]?.name || toolKey
  }
  if (typeof toolKey === 'object') {
    return toolKey.name || toolKey.tool || 'Unknown tool'
  }
  return 'Unknown tool'
}

function getToolPricingUrl(toolKey) {
  const mapping = {
    cursor: 'https://www.cursor.com/pricing',
    'github-copilot': 'https://github.com/features/copilot',
    claude: 'https://www.anthropic.com/pricing',
    chatgpt: 'https://openai.com/pricing',
    'anthropic-api': 'https://www.anthropic.com/pricing',
    'openai-api': 'https://openai.com/pricing',
    gemini: 'https://gemini.com/pricing',
    windsurf: 'https://www.windsurf.ai/pricing',
  }
  if (typeof toolKey === 'string' && mapping[toolKey]) return mapping[toolKey]
  return `https://www.${String(toolKey).replace(/[^a-z0-9]/gi, '')}.com/pricing`
}

function parseJsonField(field) {
  if (!field) return []
  if (Array.isArray(field)) return field
  try {
    return JSON.parse(field)
  } catch {
    return []
  }
}

export default async function handler(req, res) {
  const isGet = req.method === 'GET'
  const isPost = req.method === 'POST'

  if (!isGet && !isPost) {
    return res.status(405).json({ error: 'Method not allowed' })
  }

  let auditResult = {}
  let formData = {}
  let userInfo = {}
  let generatedAt

  try {
    if (isPost) {
      const body = req.body || {}
      auditResult = body.auditResult || {}
      formData = body.formData || {}
      userInfo = body.userInfo || {}
      generatedAt = body.generatedAt
    } else {
      const { id } = req.query
      if (!id) {
        return res.status(400).json({ error: 'Audit ID required' })
      }

      const { data: audit, error } = await supabase
        .from('audits')
        .select('*')
        .eq('id', id)
        .single()

      if (error || !audit) {
        console.error('Audit fetch failed:', error)
        return res.status(404).json({ error: 'Audit not found' })
      }

      const recommendations = parseJsonField(audit.recommendations)
      const tools = parseJsonField(audit.tools)

      auditResult = {
        recommendations,
        totalMonthlySavings: audit.total_monthly_savings ?? 0,
        totalAnnualSavings: audit.total_annual_savings ?? 0,
        totalCurrentSpend: audit.total_current_spend ?? 0,
        isOptimal: audit.is_optimal ?? false,
      }
      formData = {
        teamSize: audit.team_size ?? 0,
        useCase: audit.use_case || 'N/A',
        tools,
      }
      userInfo = {
        fullName: audit.full_name || audit.name || '',
        email: audit.email || '',
        company: audit.company || '',
      }
      generatedAt = audit.created_at || new Date().toISOString()
    }

    const {
      recommendations = [],
      totalMonthlySavings = 0,
      totalAnnualSavings = 0,
      totalCurrentSpend = 0,
      isOptimal = false,
    } = auditResult

    const {
      teamSize = 0,
      useCase = 'N/A',
      tools = [],
    } = formData

    const {
      fullName = '',
      email = '',
      company = '',
    } = userInfo

    const reportDate = formatDate(generatedAt)
    const toolCount = Array.isArray(tools) ? tools.length : 0
    const sortedTools = Array.isArray(recommendations) ? recommendations : []

    const doc = new PDFDocument({ size: 'A4', margin: 50 })

    res.setHeader('Content-Type', 'application/pdf')
    res.setHeader('Content-Disposition', 'attachment; filename="spendaudit-report.pdf"')
    doc.pipe(res)

    const reportFooter = 'Generated by SpendAudit · Free AI spend auditing tool'
    const finishPage = () => {
      addFooter(doc, reportFooter)
      addPageNumber(doc, doc.pageNumber)
    }
    const addNewPage = () => {
      finishPage()
      doc.addPage()
    }
    const ensureRoom = (currentY, neededHeight) => {
      const pageBottom = doc.page.height - 110
      if (currentY + neededHeight > pageBottom) {
        finishPage()
        doc.addPage()
        return 60
      }
      return currentY
    }

    // Cover page
    drawPageBackground(doc, '#15803d')
    doc.fillColor('#ffffff').font('Helvetica-Bold').fontSize(32)
    doc.text('SpendAudit', 50, 80, { align: 'center', width: doc.page.width - 100 })
    doc.font('Helvetica').fontSize(18)
    doc.text('AI Spend Report', { align: 'center' })

    const coverMiddleTop = 220
    doc.font('Helvetica').fontSize(14).fillColor('#ffffff')
    if (isOptimal) {
      doc.fontSize(24).text('Your AI spend is already optimized ✓', 50, coverMiddleTop, {
        align: 'center',
        width: doc.page.width - 100,
      })
    } else {
      doc.fontSize(14).text('Potential Monthly Savings', 50, coverMiddleTop, {
        align: 'center',
        width: doc.page.width - 100,
      })
      doc.font('Helvetica-Bold').fontSize(48).text(`${formatCurrency(totalMonthlySavings)}/month`, {
        align: 'center',
        width: doc.page.width - 100,
      })
      doc.font('Helvetica').fontSize(24).text(`${formatCurrency(totalAnnualSavings)}/year`, {
        align: 'center',
        width: doc.page.width - 100,
      })
    }

    const coverCardWidth = (doc.page.width - 170) / 3
    drawStatCard(doc, 50, 380, coverCardWidth, 'Current spend', formatCurrency(totalCurrentSpend), 'per month')
    drawStatCard(doc, 60 + coverCardWidth, 380, coverCardWidth, 'Potential savings', formatCurrency(totalMonthlySavings), 'per month')
    drawStatCard(doc, 70 + coverCardWidth * 2, 380, coverCardWidth, 'Tools audited', `${toolCount}`, 'reviewed')

    const coverBottomY = 520
    doc.font('Helvetica').fontSize(10).fillColor('#ffffff')
    if (fullName) {
      doc.text(`Prepared for: ${fullName}`, 50, coverBottomY, {
        align: 'center',
        width: doc.page.width - 100,
      })
    }
    if (company) {
      doc.text(`Company: ${company}`, { align: 'center', width: doc.page.width - 100 })
    }
    doc.text(`Team size: ${teamSize} people`, { align: 'center', width: doc.page.width - 100 })
    doc.text(`Primary use case: ${useCase}`, { align: 'center', width: doc.page.width - 100 })
    doc.text(`Generated: ${reportDate}`, { align: 'center', width: doc.page.width - 100 })

    finishPage()

    // Executive summary & recommendations page
    addNewPage()
    let y = 50
    y = drawSectionHeader(doc, 'Executive Summary', y)

    doc.font('Helvetica').fontSize(10).fillColor('#4b5563')
    const summaryText = `This audit reviews ${toolCount} AI tools across ${teamSize} team members. Current monthly spend: ${formatCurrency(totalCurrentSpend)}. Identified savings potential: ${formatCurrency(totalMonthlySavings)}/month or ${formatCurrency(totalAnnualSavings)}/year.`
    doc.text(summaryText, 50, y, { width: doc.page.width - 100, lineGap: 5 })
    y = doc.y + 12

    const cardWidth = (doc.page.width - 170) / 3
    drawStatCard(doc, 50, y, cardWidth, 'Current spend', formatCurrency(totalCurrentSpend), '')
    drawStatCard(doc, 60 + cardWidth, y, cardWidth, 'Potential savings', formatCurrency(totalMonthlySavings), '')
    y = drawStatCard(doc, 70 + cardWidth * 2, y, cardWidth, 'Tools', `${toolCount}`, '')

    y += 12
    doc.font('Helvetica-Bold').fontSize(13).fillColor('#111827')
    doc.text('Top Optimization Opportunities', 50, y)
    y += 16

    const topRecommendations = sortedTools
      .filter((rec) => (rec.monthlySavings || rec.monthly_savings || 0) > 0)
      .sort((a, b) => (b.monthlySavings || b.monthly_savings || 0) - (a.monthlySavings || a.monthly_savings || 0))
      .slice(0, 3)

    if (topRecommendations.length > 0) {
      topRecommendations.forEach((rec, index) => {
        const savings = rec.monthlySavings || rec.monthly_savings || 0
        const toolName = getToolName(rec.tool || rec.toolName)
        const action = rec.recommendedAction || rec.recommended_action || rec.action || ''

        doc.font('Helvetica-Bold').fontSize(11).fillColor('#111827')
        doc.text(`${index + 1}. ${toolName} — Save ${formatCurrency(savings)}/month`, 50, y)
        y += 14
        doc.font('Helvetica').fontSize(9).fillColor('#4b5563')
        doc.text(action, 60, y, { width: doc.page.width - 120 })
        y = doc.y + 8
      })
    }

    const calloutY = y + 10
    const calloutHeight = 72
    doc.save()
    doc.roundedRect(50, calloutY, doc.page.width - 100, calloutHeight, 12)
      .fill('#f0fdf4')
    doc.fillColor('#064e3b').font('Helvetica-Bold').fontSize(11)
    doc.text('Next Step', 60, calloutY + 12)
    doc.font('Helvetica').fontSize(9).fillColor('#065f46')
    doc.text(
      'Implement the top 1-2 recommendations to maximize ROI. Validate against your current usage and re-audit in 30 days to track actual savings.',
      60,
      calloutY + 28,
      {
        width: doc.page.width - 120,
        lineGap: 3,
      }
    )
    doc.restore()

    const allToolsCount = sortedTools.length
    if (allToolsCount > 3) {
      finishPage()
      addNewPage()
      y = 50
      y = drawSectionHeader(doc, 'Full Tool Analysis', y)
      y += 8

      doc.font('Helvetica').fontSize(9).fillColor('#6b7280')
      doc.text(`All ${allToolsCount} tools reviewed in this audit:`, 50, y)
      y += 12

      sortedTools.forEach((rec) => {
        const rowHeight = 92
        y = ensureRoom(y, rowHeight)
        const toolName = getToolName(rec.tool || rec.toolName)
        const currentPlan = rec.currentPlan || rec.current_plan || 'Current plan'
        const currentSpend = rec.currentSpend || rec.current_spend || 0
        const action = rec.recommendedAction || rec.recommended_action || rec.action || 'Recommended action'
        const monthlySavings = rec.monthlySavings || rec.monthly_savings || 0
        const reason = rec.reason || ''
        y = drawCompactToolRow(doc, 50, y, toolName, currentPlan, currentSpend, action, monthlySavings, reason)
      })

      y += 6
      doc.font('Helvetica-Bold').fontSize(11).fillColor('#15803d')
      doc.text(`Total identified savings: ${formatCurrency(totalMonthlySavings)}/month`, 50, y, {
        width: doc.page.width - 100,
        align: 'right',
      })

      y += 18
      doc.font('Helvetica').fontSize(8).fillColor('#6b7280')
      doc.text('Estimates are based on published pricing. Actual savings may vary based on usage patterns and enterprise rates.', 50, y, {
        width: doc.page.width - 100,
        lineGap: 3,
      })
    }

    finishPage()
    doc.end()
  } catch (error) {
    console.error('PDF generation failed:', error)
    res.status(500).json({ error: 'PDF generation failed' })
  }
}

function drawCompactToolRow(doc, x, y, toolName, currentPlan, currentSpend, action, savings, reason) {
  const rowHeight = 88
  const width = doc.page.width - x - 50

  doc.save()
  doc.roundedRect(x, y, width, rowHeight, 10).fill('#ffffff').stroke('#d1d5db')

  doc.font('Helvetica-Bold').fontSize(11).fillColor('#111827')
  doc.text(toolName, x + 14, y + 10, { width: width - 100 })

  doc.font('Helvetica-Bold').fontSize(11).fillColor('#15803d')
  doc.text(`$${savings || 0}/mo`, x + width - 100, y + 10, { width: 86, align: 'right' })

  doc.font('Helvetica').fontSize(9).fillColor('#4b5563')
  doc.text(`Current: ${currentPlan} · $${Number(currentSpend || 0).toLocaleString()}/mo`, x + 14, y + 30)

  doc.font('Helvetica').fontSize(9).fillColor('#111827')
  doc.text(`Recommend: ${action}`, x + 14, y + 48)

  if (reason) {
    doc.font('Helvetica').fontSize(8).fillColor('#6b7280')
    doc.text(reason, x + 14, y + 62, { width: width - 28, lineGap: 2 })
  }

  doc.restore()
  return y + rowHeight + 10
}
