export function drawPageBackground(doc, color = '#15803d') {
  const { width, height } = doc.page
  doc.save()
  doc.rect(0, 0, width, height).fill(color)
  doc.restore()
}

export function drawHorizontalLine(doc, y, color = '#d1d5db', width = 1.5) {
  const left = 50
  const right = doc.page.width - 50
  doc.save()
  doc.lineWidth(width)
  doc.strokeColor(color)
  doc.moveTo(left, y).lineTo(right, y).stroke()
  doc.restore()
}

export function drawSectionHeader(doc, text, y) {
  doc.save()
  doc.font('Helvetica-Bold').fontSize(18).fillColor('#111827')
  doc.text(text, 50, y)
  const lineY = y + 24
  drawHorizontalLine(doc, lineY, '#d1d5db', 1.5)
  doc.restore()
  return lineY + 20
}

export function drawStatCard(doc, x, y, width, label, value, subtext) {
  const height = 96
  const radius = 14

  doc.save()
  doc.roundedRect(x, y, width, height, radius).fillAndStroke('#ffffff', '#d1d5db')

  doc.font('Helvetica').fontSize(10).fillColor('#6b7280')
  doc.text(label, x + 16, y + 16, { width: width - 32 })

  doc.font('Helvetica-Bold').fontSize(26).fillColor('#15803d')
  doc.text(value, x + 16, y + 36, { width: width - 32 })

  if (subtext) {
    doc.font('Helvetica').fontSize(10).fillColor('#6b7280')
    doc.text(subtext, x + 16, y + 64, { width: width - 32 })
  }

  doc.restore()
  return y + height + 18
}

export function drawToolRow(doc, x, y, toolName, currentPlan, currentSpend, action, savings, reason) {
  const rowHeight = 108
  const width = doc.page.width - x - 50
  const isOdd = Math.floor(y / (rowHeight + 16)) % 2 === 1

  doc.save()
  if (isOdd) {
    doc.roundedRect(x, y, width, rowHeight, 14).fill('#f8fafc')
  }

  doc.strokeColor('#e5e7eb').lineWidth(0.8)
  doc.roundedRect(x, y, width, rowHeight, 14).stroke()

  doc.font('Helvetica-Bold').fontSize(13).fillColor('#111827')
  doc.text(toolName, x + 18, y + 14, { width: width - 200 })

  doc.font('Helvetica-Bold').fontSize(12).fillColor('#15803d')
  doc.text(`Save ${savings ? `$${savings}` : '$0'}/mo`, x + width - 150, y + 14, {
    width: 130,
    align: 'right',
  })

  doc.font('Helvetica').fontSize(10).fillColor('#4b5563')
  doc.text(`Current: ${currentPlan} · $${Number(currentSpend || 0).toLocaleString()}/mo`, x + 18, y + 36, {
    width: width - 36,
  })
  doc.font('Helvetica').fontSize(10).fillColor('#111827')
  doc.text(`Recommendation: ${action}`, x + 18, y + 52, {
    width: width - 36,
  })
  doc.font('Helvetica').fontSize(9).fillColor('#6b7280')
  doc.text(reason || 'No additional detail provided.', x + 18, y + 70, {
    width: width - 36,
    lineGap: 3,
  })
  doc.restore()

  return y + rowHeight + 16
}

export function addPageNumber(doc, pageNum, totalPages) {
  const text = totalPages ? `Page ${pageNum} of ${totalPages}` : `Page ${pageNum}`
  doc.save()
  doc.font('Helvetica').fontSize(8).fillColor('#6b7280')
  doc.text(text, 0, doc.page.height - 40, {
    align: 'right',
    width: doc.page.width - 50,
  })
  doc.restore()
}

export function addFooter(doc, text = 'Generated by SpendAudit') {
  doc.save()
  drawHorizontalLine(doc, doc.page.height - 60, '#e5e7eb', 1)
  doc.font('Helvetica').fontSize(8).fillColor('#6b7280')
  doc.text(text, 50, doc.page.height - 50, {
    align: 'center',
    width: doc.page.width - 100,
  })
  doc.restore()
}

export function checkPageBreak(doc, currentY, neededHeight) {
  const pageBottom = doc.page.height - 80
  if (currentY + neededHeight > pageBottom) {
    doc.addPage()
    return 50
  }
  return currentY
}
